export const deliveryCloumnsMap = {
    送货单号: 'delivery_number',
    客户编号: 'customer_number',
    客户订单号: 'customer_order_number',
    货号: 'product_number',
    品名: 'product_name',
    颜色编号: 'color_number',
    颜色名称: 'color_name',
    缸号: 'dyeing_vat_number',
    卷号: 'roll_number',
    数量: 'quantity',
    '净总(KG)': 'net_total_kg',
    扣库存数: 'deducted_stock_number',
    单价: 'unit_price',
    附件费: 'accessory_fee',
    单位: 'unit',
    客户货号: 'customer_product_number',
    客户色号: 'customer_color_number',
    备注: 'remark',
    副宽: 'sub_width',
    克重: 'gram_weight',
    仓位: 'storage_location'
}